// Code generated by jtd-codegen for TypeScript v0.2.1

export type Item = Condition;

export type Condition = ConditionAnd | ConditionCondition | ConditionOr | ConditionContext | ConditionUrl;

export interface ConditionAnd {
  type: "AND";
  exprs: Condition[];
}

export interface ConditionCondition {
  type: "CONDITION";
  condition: Condition;
}

export interface ConditionOr {
  type: "OR";
  exprs: Condition[];
  value: string;
}

export interface ConditionContext {
  type: "context";
  field: string;
  operator: string;
  value: string;
}

export interface ConditionUrl {
  type: "url";
  operator: string;
  value: string;
}
